spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/oop3"
    username: postgres
    password: 12903478
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect


